name: 'ga4'
version: '5.1.0'
config-version: 2
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  ga4:
    +materialized: view
    marts:
      +materialized: table

vars:
  ga4:
    source_project: "ga4zodoganhou" # Project that contains raw GA4 data
    property_ids: [313358243] # Array of properties to process
    start_date: "20240122" # Earliest date to load
    static_incremental_days: 3 # Number of days to scan and reprocess on each run
